use super::mcp::*;
use super::*;
use super::{agent_skill, command};
use std::collections::{BTreeMap, HashMap};
use std::path::PathBuf;

#[allow(clippy::crate_in_macro_def)]
#[macro_export]
macro_rules! daemon_api {
    ($consumer:ident) => { $consumer! {
        crew_create(input: CreateCrewInput => CreateCrewInput = { input }) -> Crew [false] => |core: &crate::AppCore, input: CreateCrewInput| { crate::ops::crew::crew_create(core, input) };
        crew_delete(id: &str => String = { id.to_owned() }) -> () [false] => |core: &crate::AppCore, id: String| { crate::ops::crew::crew_delete(core, &id) };
        crew_get(id: &str => String = { id.to_owned() }) -> Crew [false] => |core: &crate::AppCore, id: String| { crate::ops::crew::crew_get(core, &id) };
        crew_list(page: i64 => i64 = { page }, page_size: i64 => i64 = { page_size }, query: &str => String = { query.to_owned() }) -> ListPage<CrewListItem> [false] => |core: &crate::AppCore, page: i64, page_size: i64, query: String| { crate::ops::crew::crew_list(core, page, page_size, &query) };
        crew_update(id: &str => String = { id.to_owned() }, input: UpdateCrewInput => UpdateCrewInput = { input }) -> Crew [false] => |core: &crate::AppCore, id: String, input: UpdateCrewInput| { crate::ops::crew::crew_update(core, &id, input) };
        mission_archive_impl(id: String => String = { id }) -> Mission [false] => |core: &crate::AppCore, id: String| { crate::daemon::block_on(crate::ops::mission::mission_archive_impl(core, id)).map(|mission| { core.events.emit("mission/changed", &serde_json::json!({ "mission_id": mission.id })); mission }) };
        mission_attach(mission_id: &str => String = { mission_id.to_owned() }) -> Mission [false] => |core: &crate::AppCore, mission_id: String| { crate::daemon::block_on(crate::ops::mission::mission_attach(core, &mission_id)) };
        mission_delete(id: &str => String = { id.to_owned() }) -> () [false] => |core: &crate::AppCore, id: String| { crate::ops::mission::mission_delete(core, &id) };
        mission_events_replay(mission_id: &str => String = { mission_id.to_owned() }) -> Vec<Event> [false] => |core: &crate::AppCore, mission_id: String| { crate::ops::mission::mission_events_replay(core, &mission_id) };
        mission_get(id: &str => String = { id.to_owned() }) -> Mission [true] => |core: &crate::AppCore, id: String| { crate::ops::mission::mission_get(core, &id) };
        mission_grid_hint_set(cols: u16 => u16 = { cols }, rows: u16 => u16 = { rows }) -> () [false] => |core: &crate::AppCore, cols: u16, rows: u16| { crate::ops::mission::mission_grid_hint_set(core, cols, rows) };
        mission_list_archived(crew_id: Option<String> => Option<String> = { crew_id }) -> Vec<Mission> [false] => |core: &crate::AppCore, crew_id: Option<String>| { crate::ops::mission::mission_list_archived(core, crew_id) };
        mission_list_summary_impl(crew_id: Option<String> => Option<String> = { crew_id }) -> Vec<MissionSummary> [false] => |core: &crate::AppCore, crew_id: Option<String>| { crate::daemon::block_on(crate::ops::mission::mission_list_summary_impl(core, crew_id)) };
        mission_pin_impl(id: String => String = { id }, pinned: bool => bool = { pinned }) -> Mission [false] => |core: &crate::AppCore, id: String, pinned: bool| { crate::daemon::block_on(crate::ops::mission::mission_pin_impl(core, id, pinned)).map(|mission| { core.events.emit("mission/changed", &serde_json::json!({ "mission_id": mission.id })); mission }) };
        mission_post_impl(input: PostMessageInput => PostMessageInput = { input }) -> Event [false] => |core: &crate::AppCore, input: PostMessageInput| { crate::daemon::block_on(crate::ops::mission::mission_post_impl(core, input)) };
        mission_rename_impl(id: String => String = { id }, title: String => String = { title }) -> Mission [false] => |core: &crate::AppCore, id: String, title: String| { crate::daemon::block_on(crate::ops::mission::mission_rename_impl(core, id, title)).map(|mission| { core.events.emit("mission/changed", &serde_json::json!({ "mission_id": mission.id })); mission }) };
        mission_signal_impl(input: PostSignalInput => PostSignalInput = { input }) -> Event [false] => |core: &crate::AppCore, input: PostSignalInput| { crate::daemon::block_on(crate::ops::mission::mission_signal_impl(core, input)) };
        mission_start_impl_with_size(input: MissionStart => MissionStart = { input }, initial_size: Option<(u16, u16)> => Option<(u16, u16)> = { initial_size }) -> StartMissionOutput [false] => |core: &crate::AppCore, input: MissionStart, initial_size: Option<(u16, u16)>| { crate::daemon::block_on(crate::ops::mission::mission_start_impl_with_size(core, input, initial_size)) };
        mission_stop_impl(id: String => String = { id }) -> Mission [false] => |core: &crate::AppCore, id: String| { crate::daemon::block_on(crate::ops::mission::mission_stop_impl(core, id)) };
        mission_unarchive(id: String => String = { id }) -> Mission [false] => |core: &crate::AppCore, id: String| { crate::daemon::block_on(crate::ops::mission::mission_unarchive(core, id)) };
        mark_direct_sessions_viewed(session_ids: &[String] => Vec<String> = { session_ids.to_vec() }) -> () [false] => |core: &crate::AppCore, session_ids: Vec<String>| { crate::ops::node::mark_direct_sessions_viewed(core, &session_ids) };
        node_list() -> Vec<NodeRow> [false] => |core: &crate::AppCore| { crate::ops::node::node_list(core) };
        node_mark_viewed(window_label: &str => String = { window_label.to_owned() }, id: &str => String = { id.to_owned() }, member_ids: Vec<String> => Vec<String> = { member_ids }, viewed_session_id: Option<&str> => Option<String> = { viewed_session_id.map(str::to_owned) }) -> Option<NodeRow> [false] => |core: &crate::AppCore, window_label: String, id: String, member_ids: Vec<String>, viewed_session_id: Option<String>| { crate::ops::node::node_mark_viewed(core, &window_label, &id, member_ids, viewed_session_id.as_deref()) };
        node_mission_layout_set(node_id: &str => String = { node_id.to_owned() }, layout: String => String = { layout }) -> NodeRow [false] => |core: &crate::AppCore, node_id: String, layout: String| { crate::ops::node::node_mission_layout_set(core, &node_id, layout) };
        node_move(id: String => String = { id }, parent_id: Option<String> => Option<String> = { parent_id }, ordered_ids: Vec<String> => Vec<String> = { ordered_ids }) -> Vec<NodeRow> [false] => |core: &crate::AppCore, id: String, parent_id: Option<String>, ordered_ids: Vec<String>| { crate::ops::node::node_move(core, id, parent_id, ordered_ids) };
        node_rename(id: String => String = { id }, name: String => String = { name }) -> NodeRow [false] => |core: &crate::AppCore, id: String, name: String| { crate::ops::node::node_rename(core, id, name) };
        node_reorder_pinned(ordered_ids: Vec<String> => Vec<String> = { ordered_ids }) -> Vec<NodeRow> [false] => |core: &crate::AppCore, ordered_ids: Vec<String>| { crate::ops::node::node_reorder_pinned(core, ordered_ids) };
        node_set_pinned(id: String => String = { id }, pinned: bool => bool = { pinned }) -> NodeRow [false] => |core: &crate::AppCore, id: String, pinned: bool| { crate::ops::node::node_set_pinned(core, id, pinned) };
        node_tab_delete(node_id: &str => String = { node_id.to_owned() }) -> () [false] => |core: &crate::AppCore, node_id: String| { crate::ops::node::node_tab_delete(core, &node_id) };
        node_tab_upsert(input: NodeTabUpsertInput => NodeTabUpsertInput = { input }) -> NodeRow [false] => |core: &crate::AppCore, input: NodeTabUpsertInput| { crate::ops::node::node_tab_upsert(core, input) };
        project_create(name: String => String = { name }, cwd: String => String = { cwd }) -> ProjectRow [false] => |core: &crate::AppCore, name: String, cwd: String| { crate::ops::project::project_create(core, name, cwd) };
        project_delete(id: String => String = { id }) -> ProjectDeleteOutcome [false] => |core: &crate::AppCore, id: String| { crate::daemon::block_on(crate::ops::project::project_delete(core, id)) };
        project_list() -> Vec<ProjectRow> [false] => |core: &crate::AppCore| { crate::ops::project::project_list(core) };
        project_rename(id: String => String = { id }, name: String => String = { name }) -> ProjectRow [false] => |core: &crate::AppCore, id: String, name: String| { crate::ops::project::project_rename(core, id, name) };
        role_activity(id: &str => String = { id.to_owned() }) -> RoleActivity [false] => |core: &crate::AppCore, id: String| { crate::ops::role::role_activity(core, &id) };
        role_create(input: CreateRoleInput => CreateRoleInput = { input }) -> Role [false] => |core: &crate::AppCore, input: CreateRoleInput| { crate::ops::role::role_create(core, input) };
        role_delete(id: &str => String = { id.to_owned() }) -> () [false] => |core: &crate::AppCore, id: String| { crate::ops::role::role_delete(core, &id) };
        role_get(id: &str => String = { id.to_owned() }) -> Role [true] => |core: &crate::AppCore, id: String| { crate::ops::role::role_get(core, &id) };
        role_get_by_handle(handle: &str => String = { handle.to_owned() }) -> Role [true] => |core: &crate::AppCore, handle: String| { crate::ops::role::role_get_by_handle(core, &handle) };
        role_list() -> Vec<Role> [false] => |core: &crate::AppCore| { crate::ops::role::role_list(core) };
        role_list_with_activity(page: i64 => i64 = { page }, page_size: i64 => i64 = { page_size }, query: &str => String = { query.to_owned() }) -> ListPage<RoleWithActivity> [false] => |core: &crate::AppCore, page: i64, page_size: i64, query: String| { crate::ops::role::role_list_with_activity(core, page, page_size, &query) };
        role_update(id: &str => String = { id.to_owned() }, input: UpdateRoleInput => UpdateRoleInput = { input }) -> Role [false] => |core: &crate::AppCore, id: String, input: UpdateRoleInput| { crate::ops::role::role_update(core, &id, input) };
        runtime_catalog() -> Vec<RuntimeCatalogEntry> [false] => |core: &crate::AppCore| { crate::ops::runtime::runtime_catalog(core) };
        runtime_check_updates(force: bool => bool = { force }) -> () [false] => |core: &crate::AppCore, force: bool| { Ok(crate::ops::runtime::runtime_check_updates(core, force)) };
        runtime_clear_override(runtime: Runtime => Runtime = { runtime }) -> RuntimeStatusResponse [false] => |core: &crate::AppCore, runtime: Runtime| { crate::ops::runtime::runtime_clear_override(core, runtime) };
        runtime_probe_version(runtime: Runtime => Runtime = { runtime }) -> Option<String> [false] => |core: &crate::AppCore, runtime: Runtime| { Ok(crate::ops::runtime::runtime_probe_version(core, runtime)) };
        runtime_refresh(model_runtimes: &[Runtime] => Vec<Runtime> = { model_runtimes.to_vec() }) -> RuntimeStatusResponse [false] => |core: &crate::AppCore, model_runtimes: Vec<Runtime>| { crate::ops::runtime::runtime_refresh(core, &model_runtimes) };
        runtime_refresh_models(runtimes: &[Runtime] => Vec<Runtime> = { runtimes.to_vec() }) -> () [false] => |core: &crate::AppCore, runtimes: Vec<Runtime>| { Ok(crate::ops::runtime::runtime_refresh_models(core, &runtimes)) };
        runtime_request_models(runtimes: &[Runtime] => Vec<Runtime> = { runtimes.to_vec() }) -> () [false] => |core: &crate::AppCore, runtimes: Vec<Runtime>| { Ok(crate::ops::runtime::runtime_request_models(core, &runtimes)) };
        runtime_set_override(runtime: Runtime => Runtime = { runtime }, path: &str => String = { path.to_owned() }) -> std::result::Result<RuntimeStatusResponse, OverrideValidationError> [false] => |core: &crate::AppCore, runtime: Runtime, path: String| { Ok(crate::ops::runtime::runtime_set_override(core, runtime, &path)) };
        runtime_status_list() -> RuntimeStatusResponse [false] => |core: &crate::AppCore| { crate::ops::runtime::runtime_status_list(core) };
        live_session_counts() -> HashMap<Runtime, usize> [false] => |core: &crate::AppCore| { crate::ops::session::live_session_counts(core) };
        session_activity_snapshot() -> BTreeMap<String, SessionActivityState> [true] => |core: &crate::AppCore| { Ok(crate::ops::session::session_activity_snapshot(core)) };
        session_archive(session_id: &str => String = { session_id.to_owned() }) -> () [false] => |core: &crate::AppCore, session_id: String| { crate::ops::session::session_archive(core, &session_id) };
        session_close(session_id: &str => String = { session_id.to_owned() }) -> () [false] => |core: &crate::AppCore, session_id: String| { crate::ops::session::session_close(core, &session_id) };
        session_delete(session_id: &str => String = { session_id.to_owned() }) -> () [false] => |core: &crate::AppCore, session_id: String| { crate::ops::session::session_delete(core, &session_id) };
        session_fork(source_session_id: &str => String = { source_session_id.to_owned() }, title: Option<String> => Option<String> = { title }, cols: Option<u16> => Option<u16> = { cols }, rows: Option<u16> => Option<u16> = { rows }) -> SpawnedSession [false] => |core: &crate::AppCore, source_session_id: String, title: Option<String>, cols: Option<u16>, rows: Option<u16>| { crate::ops::session::session_fork(core, &source_session_id, title, cols, rows) };
        session_get(session_id: &str => String = { session_id.to_owned() }) -> Option<DirectSessionEntry> [false] => |core: &crate::AppCore, session_id: String| { crate::ops::session::session_get(core, &session_id) };
        session_kill(session_id: &str => String = { session_id.to_owned() }) -> () [false] => |core: &crate::AppCore, session_id: String| { crate::ops::session::session_kill(core, &session_id) };
        session_list(mission_id: &str => String = { mission_id.to_owned() }) -> Vec<SessionRow> [false] => |core: &crate::AppCore, mission_id: String| { crate::ops::session::session_list(core, &mission_id) };
        session_list_archived() -> Vec<DirectSessionEntry> [false] => |core: &crate::AppCore| { crate::ops::session::session_list_archived(core) };
        session_list_recent_direct() -> Vec<DirectSessionEntry> [false] => |core: &crate::AppCore| { crate::ops::session::session_list_recent_direct(core) };
        session_pin(session_id: &str => String = { session_id.to_owned() }, pinned: bool => bool = { pinned }) -> () [false] => |core: &crate::AppCore, session_id: String, pinned: bool| { crate::ops::session::session_pin(core, &session_id, pinned) };
        session_rename(session_id: &str => String = { session_id.to_owned() }, title: Option<String> => Option<String> = { title }) -> () [false] => |core: &crate::AppCore, session_id: String, title: Option<String>| { crate::ops::session::session_rename(core, &session_id, title) };
        session_restart(session_id: &str => String = { session_id.to_owned() }, cols: Option<u16> => Option<u16> = { cols }, rows: Option<u16> => Option<u16> = { rows }) -> SpawnedSession [false] => |core: &crate::AppCore, session_id: String, cols: Option<u16>, rows: Option<u16>| { crate::ops::session::session_restart(core, &session_id, cols, rows) };
        session_resume(session_id: &str => String = { session_id.to_owned() }, cols: Option<u16> => Option<u16> = { cols }, rows: Option<u16> => Option<u16> = { rows }) -> SpawnedSession [false] => |core: &crate::AppCore, session_id: String, cols: Option<u16>, rows: Option<u16>| { crate::ops::session::session_resume(core, &session_id, cols, rows) };
        session_resume_on_launch(session_id: &str => String = { session_id.to_owned() }, cols: Option<u16> => Option<u16> = { cols }, rows: Option<u16> => Option<u16> = { rows }) -> SpawnedSession [false] => |core: &crate::AppCore, session_id: String, cols: Option<u16>, rows: Option<u16>| { crate::ops::session::session_resume_on_launch(core, &session_id, cols, rows) };
        session_shell_has_foreground_process(session_id: &str => String = { session_id.to_owned() }) -> bool [false] => |core: &crate::AppCore, session_id: String| { crate::ops::session::session_shell_has_foreground_process(core, &session_id) };
        session_start_direct(role_id: String => String = { role_id }, runtime: Option<String> => Option<String> = { runtime }, model: Option<String> => Option<String> = { model }, effort: Option<String> => Option<String> = { effort }, scope: ProjectScope => ProjectScope = { scope }, cwd: Option<String> => Option<String> = { cwd }, cols: Option<u16> => Option<u16> = { cols }, rows: Option<u16> => Option<u16> = { rows }) -> SpawnedSession [false] => |core: &crate::AppCore, role_id: String, runtime: Option<String>, model: Option<String>, effort: Option<String>, scope: ProjectScope, cwd: Option<String>, cols: Option<u16>, rows: Option<u16>| { crate::ops::session::session_start_direct(core, role_id, runtime, model, effort, scope, cwd, cols, rows) };
        session_start_direct_with_speed(role_id: String => String = { role_id }, runtime: Option<String> => Option<String> = { runtime }, model: Option<String> => Option<String> = { model }, effort: Option<String> => Option<String> = { effort }, speed: Option<CodexSpeed> => Option<CodexSpeed> = { speed }, scope: ProjectScope => ProjectScope = { scope }, cwd: Option<String> => Option<String> = { cwd }, cols: Option<u16> => Option<u16> = { cols }, rows: Option<u16> => Option<u16> = { rows }) -> SpawnedSession [false] => |core: &crate::AppCore, role_id: String, runtime: Option<String>, model: Option<String>, effort: Option<String>, speed: Option<CodexSpeed>, scope: ProjectScope, cwd: Option<String>, cols: Option<u16>, rows: Option<u16>| { crate::ops::session::session_start_direct_with_speed(core, role_id, runtime, model, effort, speed, scope, cwd, cols, rows) };
        session_start_runtime_with_speed(runtime: &str => String = { runtime.to_owned() }, scope: ProjectScope => ProjectScope = { scope }, cwd: Option<String> => Option<String> = { cwd }, cols: Option<u16> => Option<u16> = { cols }, rows: Option<u16> => Option<u16> = { rows }, model: Option<String> => Option<String> = { model }, effort: Option<String> => Option<String> = { effort }, speed: Option<CodexSpeed> => Option<CodexSpeed> = { speed }) -> StartDirectSessionOutput [false] => |core: &crate::AppCore, runtime: String, scope: ProjectScope, cwd: Option<String>, cols: Option<u16>, rows: Option<u16>, model: Option<String>, effort: Option<String>, speed: Option<CodexSpeed>| { crate::ops::session::session_start_runtime_with_speed(core, &runtime, scope, cwd, cols, rows, model, effort, speed) };
        session_start_shell_in(scope: ProjectScope => ProjectScope = { scope }, cwd: Option<String> => Option<String> = { cwd }, cols: Option<u16> => Option<u16> = { cols }, rows: Option<u16> => Option<u16> = { rows }) -> SpawnedSession [false] => |core: &crate::AppCore, scope: ProjectScope, cwd: Option<String>, cols: Option<u16>, rows: Option<u16>| { crate::ops::session::session_start_shell_in(core, scope, cwd, cols, rows) };
        session_status_snapshot() -> BTreeMap<String, AgentStatus> [false] => |core: &crate::AppCore| { crate::ops::session::session_status_snapshot(core) };
        session_take_resume_on_launch(session_id: &str => String = { session_id.to_owned() }) -> bool [false] => |core: &crate::AppCore, session_id: String| { crate::ops::session::session_take_resume_on_launch(core, &session_id) };
        session_unarchive(session_id: &str => String = { session_id.to_owned() }) -> () [false] => |core: &crate::AppCore, session_id: String| { crate::ops::session::session_unarchive(core, &session_id) };
        role_crews_list(role_id: &str => String = { role_id.to_owned() }) -> Vec<CrewMembership> [false] => |core: &crate::AppCore, role_id: String| { crate::ops::slot::role_crews_list(core, &role_id) };
        slot_create(input: CreateSlotInput => CreateSlotInput = { input }) -> SlotWithRole [false] => |core: &crate::AppCore, input: CreateSlotInput| { crate::ops::slot::slot_create(core, input) };
        slot_delete(slot_id: &str => String = { slot_id.to_owned() }) -> () [false] => |core: &crate::AppCore, slot_id: String| { crate::ops::slot::slot_delete(core, &slot_id) };
        slot_list(crew_id: &str => String = { crew_id.to_owned() }) -> Vec<SlotWithRole> [false] => |core: &crate::AppCore, crew_id: String| { crate::ops::slot::slot_list(core, &crew_id) };
        slot_reorder(crew_id: &str => String = { crew_id.to_owned() }, ordered_slot_ids: Vec<String> => Vec<String> = { ordered_slot_ids }) -> Vec<SlotWithRole> [false] => |core: &crate::AppCore, crew_id: String, ordered_slot_ids: Vec<String>| { crate::ops::slot::slot_reorder(core, &crew_id, ordered_slot_ids) };
        slot_set_lead(slot_id: &str => String = { slot_id.to_owned() }) -> SlotWithRole [false] => |core: &crate::AppCore, slot_id: String| { crate::ops::slot::slot_set_lead(core, &slot_id) };
        slot_update(slot_id: &str => String = { slot_id.to_owned() }, input: UpdateSlotInput => UpdateSlotInput = { input }) -> SlotWithRole [false] => |core: &crate::AppCore, slot_id: String, input: UpdateSlotInput| { crate::ops::slot::slot_update(core, &slot_id, input) };
        mark_blurred(label: &str => String = { label.to_owned() }) -> () [false] => |core: &crate::AppCore, label: String| { Ok(crate::ops::window::mark_blurred(core, &label)) };
        mark_focused(label: &str => String = { label.to_owned() }) -> () [false] => |core: &crate::AppCore, label: String| { crate::ops::window::mark_focused(core, &label) };
        report_subjects(label: &str => String = { label.to_owned() }, subjects: Vec<Subject> => Vec<Subject> = { subjects }, viewed_session_id: Option<&str> => Option<String> = { viewed_session_id.map(str::to_owned) }) -> () [false] => |core: &crate::AppCore, label: String, subjects: Vec<Subject>, viewed_session_id: Option<String>| { crate::ops::window::report_subjects(core, &label, subjects, viewed_session_id.as_deref()) };
        unregister(label: &str => String = { label.to_owned() }) -> () [false] => |core: &crate::AppCore, label: String| { Ok(crate::ops::window::unregister(core, &label)) };

        crew_list_all() -> Vec<CrewListItem> [false] => |core: &crate::AppCore| { { let conn = core.db.get()?; crate::ops::crew::list(&conn) } };
        window_snapshot() -> Vec<WindowEntry> [true] => |core: &crate::AppCore| { Ok(core.windows.snapshot()) };
        window_register(label: &str => String = { label.to_owned() }) -> () [false] => |core: &crate::AppCore, label: String| { core.windows.register(&label); core.broadcast_focus_map(); Ok(()) };
        usage_snapshot() -> UsageSnapshot [true] => |core: &crate::AppCore| { Ok(core.usage.snapshot()) };
        usage_set_enabled(runtimes: Vec<Runtime> => Vec<Runtime> = { runtimes }) -> bool [false] => |core: &crate::AppCore, runtimes: Vec<Runtime>| { let changed = core.usage.set_enabled(runtimes); if changed { core.usage.request_refresh(core.clone(), RefreshReason::Button); } Ok(changed) };
        usage_refresh(reason: RefreshReason => RefreshReason = { reason }) -> () [false] => |core: &crate::AppCore, reason: RefreshReason| { core.usage.request_refresh(core.clone(), reason); Ok(()) };
        discovery_snapshot() -> DiscoverySnapshot [true] => |core: &crate::AppCore| { crate::daemon::discovery_snapshot(core) };
        skill_catalogs() -> Vec<skills::SkillCatalog> [false] => |core: &crate::AppCore| { Ok(crate::ops::skills::skill_catalogs(core)) };
        skill_set_global_enabled(runtime: Runtime => Runtime = { runtime }, path: &std::path::Path => PathBuf = { path.to_path_buf() }, enabled: bool => bool = { enabled }) -> skills::SkillCatalog [false] => |core: &crate::AppCore, runtime: Runtime, path: PathBuf, enabled: bool| { crate::ops::skills::set_global_enabled(core, runtime, &path, enabled) };
        skill_read(runtime: Runtime => Runtime = { runtime }, path: &std::path::Path => PathBuf = { path.to_path_buf() }) -> String [false] => |core: &crate::AppCore, runtime: Runtime, path: PathBuf| { crate::ops::skills::read_skill(core, runtime, &path) };
        skill_save(runtime: Runtime => Runtime = { runtime }, path: &std::path::Path => PathBuf = { path.to_path_buf() }, content: &str => String = { content.to_owned() }) -> skills::SkillEntry [false] => |core: &crate::AppCore, runtime: Runtime, path: PathBuf, content: String| { crate::ops::skills::save_skill(core, runtime, &path, &content) };
        mcp_catalog(home: &std::path::Path => PathBuf = { home.to_path_buf() }) -> McpCatalog [false] => |_core: &crate::AppCore, home: PathBuf| { crate::ops::mcp::mcp_catalog(&home) };
        mcp_copy_server(home: &std::path::Path => PathBuf = { home.to_path_buf() }, from: McpClientId => McpClientId = { from }, to: McpClientId => McpClientId = { to }, name: &str => String = { name.to_owned() }) -> () [false] => |_core: &crate::AppCore, home: PathBuf, from: McpClientId, to: McpClientId, name: String| { crate::ops::mcp::mcp_copy_server(&home, from, to, &name) };
        mcp_remove_server(home: &std::path::Path => PathBuf = { home.to_path_buf() }, client: McpClientId => McpClientId = { client }, name: &str => String = { name.to_owned() }) -> () [false] => |_core: &crate::AppCore, home: PathBuf, client: McpClientId, name: String| { crate::ops::mcp::mcp_remove_server(&home, client, &name) };
        mcp_validate_edit(client: McpClientId => McpClientId = { client }, name: &str => String = { name.to_owned() }, text: &str => String = { text.to_owned() }, also: &[McpClientId] => Vec<McpClientId> = { also.to_vec() }) -> () [false] => |_core: &crate::AppCore, client: McpClientId, name: String, text: String, also: Vec<McpClientId>| { crate::ops::mcp::validate_mcp_edit(client, &name, &text, &also) };
        mcp_edit_server(home: &std::path::Path => PathBuf = { home.to_path_buf() }, client: McpClientId => McpClientId = { client }, name: &str => String = { name.to_owned() }, text: &str => String = { text.to_owned() }, also: &[McpClientId] => Vec<McpClientId> = { also.to_vec() }) -> () [false] => |_core: &crate::AppCore, home: PathBuf, client: McpClientId, name: String, text: String, also: Vec<McpClientId>| { crate::ops::mcp::mcp_edit_server(&home, client, &name, &text, &also) };

        agent_skill_remove(home: &std::path::Path => PathBuf = { home.to_path_buf() }, debug: bool => bool = { debug }) -> Vec<bool> [false] => |_core: &crate::AppCore, home: PathBuf, debug: bool| { crate::agent_skill::remove(&home, debug) };
        agent_skill_status_root(root: &std::path::Path => PathBuf = { root.to_path_buf() }, debug: bool => bool = { debug }, expected: &str => String = { expected.to_owned() }) -> agent_skill::SkillRootStatus [false] => |_core: &crate::AppCore, root: PathBuf, debug: bool, expected: String| { Ok(crate::agent_skill::status_root(&root, debug, &expected)) };
        agent_skill_install_root(root: &std::path::Path => PathBuf = { root.to_path_buf() }, debug: bool => bool = { debug }, content: &str => String = { content.to_owned() }) -> agent_skill::InstallOutcome [false] => |_core: &crate::AppCore, root: PathBuf, debug: bool, content: String| { crate::agent_skill::install_root(&root, debug, &content) };
        mcp_client_status(client: McpClientId => McpClientId = { client }, path: &std::path::Path => PathBuf = { path.to_path_buf() }, binary: &str => String = { binary.to_owned() }) -> McpClientStatus [false] => |_core: &crate::AppCore, client: McpClientId, path: PathBuf, binary: String| { crate::ops::mcp::McpClientExt::status_at(client, &path, &binary) };
        mcp_remove_runner_entry(client: McpClientId => McpClientId = { client }, path: &std::path::Path => PathBuf = { path.to_path_buf() }, binary: &str => String = { binary.to_owned() }) -> bool [false] => |_core: &crate::AppCore, client: McpClientId, path: PathBuf, binary: String| { crate::ops::mcp::remove_runner_entry(client, &path, &binary) };
        command_directory_writable(path: &std::path::Path => PathBuf = { path.to_path_buf() }) -> bool [false] => |_core: &crate::AppCore, path: PathBuf| { Ok(crate::cli_install::directory_writable(&path)) };
        command_status(inputs: &command::CommandInstallInputs => command::CommandInstallInputs = { inputs.clone() }, system: bool => bool = { system }) -> (command::RunnerCommandStatus, bool, PathBuf) [false] => |_core: &crate::AppCore, inputs: command::CommandInstallInputs, system: bool| { crate::daemon::commands::status(&inputs, system) };
        command_install_default(inputs: &command::CommandInstallInputs => command::CommandInstallInputs = { inputs.clone() }, system: bool => bool = { system }) -> command::CommandActionOutcome [false] => |_core: &crate::AppCore, inputs: command::CommandInstallInputs, system: bool| { crate::daemon::commands::install_default(&inputs, system) };
        command_action(inputs: &command::CommandInstallInputs => command::CommandInstallInputs = { inputs.clone() }, install: bool => bool = { install }, system: bool => bool = { system }) -> command::CommandActionOutcome [false] => |_core: &crate::AppCore, inputs: command::CommandInstallInputs, install: bool, system: bool| { crate::daemon::commands::action(&inputs, install, system) };


        app_woke() -> () [false] => |core: &crate::AppCore| { core.events.emit("app/woke", &()); Ok(()) };
        window_set_mission(label: &str => String = { label.to_owned() }, id: &str => String = { id.to_owned() }, focused: bool => bool = { focused }) -> () [false] => |core: &crate::AppCore, label: String, id: String, focused: bool| { core.windows.set_subjects(&label, vec![Subject::Mission(id)]); if focused { core.windows.mark_focused(&label); } else { core.windows.mark_blurred(&label); } core.broadcast_focus_map(); Ok(()) };
        consume_resume_on_launch(enabled: bool => bool = { enabled }, sizes: HashMap<String, (u16, u16)> => HashMap<String, (u16, u16)> = { sizes }, fallback: (u16, u16) => (u16, u16) = { fallback }) -> AutoResumeReport [false] => |core: &crate::AppCore, enabled: bool, sizes: HashMap<String, (u16, u16)>, fallback: (u16, u16)| { crate::daemon::resume::consume_resume_on_launch(core, enabled, |id| sizes.get(id).copied().or(Some(fallback))) };
        direct_chat_path() -> String [true] => |core: &crate::AppCore| { let snapshot = crate::daemon::discovery_snapshot(core)?; Ok(crate::runtime_status::direct_chat_path(&snapshot.shell_env)) };
        file_link_environment() -> (String, HashMap<String, bool>) [false] => |core: &crate::AppCore| { let snapshot = crate::daemon::discovery_snapshot(core)?; let path = crate::runtime_status::direct_chat_path(&snapshot.shell_env); let found = ["zed", "code", "cursor"].into_iter().map(|command| (command.to_owned(), crate::runtime_status::find_executable(command, &path).is_some())).collect(); Ok((path, found)) };

        session_clipboard_file_paths() -> Vec<String> [false] => |_core: &crate::AppCore| { Ok(crate::ops::session::session_clipboard_file_paths()) };
        session_paste_image(bytes: Vec<u8> => Vec<u8> = { bytes }, mime_type: &str => String = { mime_type.to_owned() }) -> () [false] => |_core: &crate::AppCore, bytes: Vec<u8>, mime_type: String| { crate::ops::session::session_paste_image(bytes, &mime_type) };
        session_details() -> BTreeMap<String, DirectSessionEntry> [false] =>
        |core: &crate::AppCore| { crate::ops::session::session_list_recent_direct(core)?.into_iter().filter_map(|entry| match crate::ops::session::session_get(core, &entry.session_id) { Ok(Some(detail)) => Some(Ok((entry.session_id, detail))), Ok(None) => None, Err(error) => Some(Err(error)) }).collect::<crate::error::Result<BTreeMap<String, DirectSessionEntry>>>() };
    } };
}

macro_rules! define_api {
    ($( $name:ident($( $arg:ident: $client_ty:ty => $wire_ty:ty = $convert:block ),*) -> $out:ty [$fast:literal] => $handler:expr; )*) => {
        #[allow(non_camel_case_types)]
        #[derive(Debug, serde::Serialize, serde::Deserialize)]
        pub enum Request { $( $name { $( $arg: $wire_ty ),* }, )* }
        #[allow(non_camel_case_types)]
        #[derive(Debug, serde::Serialize, serde::Deserialize)]
        pub enum Response { $( $name(Result<$out, ClientError>), )* }
        pub const API_OPERATIONS: &[(&str, bool)] = &[$((stringify!($name), $fast)),*];
        impl Request {
            pub fn is_fast(&self) -> bool { match self { $( Self::$name { .. } => $fast, )* } }
        }
        impl DaemonClient { $(
            #[allow(clippy::too_many_arguments)]
            pub fn $name(&self, $( $arg: $client_ty ),*) -> Result<$out, ClientError> {
                let response = self.transport.call(Request::$name { $( $arg: $convert ),* })?;
                match response {
                    Response::$name(result) => result,
                    _ => Err(ClientError::msg(concat!("unexpected response to ", stringify!($name)))),
                }
            }
        )* }
    };
}
crate::daemon_api!(define_api);
